baseURL = "https://blog.rokcso.com/"
languageCode = "en-US"
title = "rok's Blog"
theme = "typo"


# >>> params - Start <<<

# All parameter configurations are after [params]
# æ‰€æœ‰å‚æ•°é…ç½®éƒ½åœ¨ [params] ä¹‹åŽ
[params]

# Meta description
# é¡µé¢ description å…ƒæ•°æ®
description = "è¿™é‡Œæ˜¯ä¸»é¡µæè¿°"

# Show breadcrumbs
# æ˜¯å¦å±•ç¤ºé¢åŒ…å±‘ï¼ˆé¡µé¢è·¯å¾„ï¼‰
breadcrumbs = false

# Appearance settings, enumeration: auto | light | dark
# æ˜Žæš—ä¸»é¢˜ï¼Œæžšä¸¾ï¼šauto | light | dark
theme = "auto"

# >>> Homepage - Start <<<

# Intro on main page, content is markdown
# é¦–é¡µçš„è‡ªæˆ‘ä»‹ç»ï¼Œå†…å®¹æ˜¯ Markdown æ ¼å¼
homeIntroTitle = "Hi! ðŸ‘‹"
homeIntroContent = """
This is rokcso. I know a little about development and design. I build for myself first.
"""

# Collection to display on home
# åœ¨é¦–é¡µå±•ç¤ºåˆé›†
homeCollectionTitle = "Posts"
homeCollection = "posts"

# >>> Homepage - End <<<

# >>> Collection - Start <<<

# Maximum number of posts per page
# æ¯é¡µæœ€å¤§æ–‡ç« æ•°
paginationSize = 100

# Date format
# æ—¥æœŸæ ¼å¼
listDateFormat = "2 Jan 2006"

# Summary
# æ–‡ç« æ‘˜è¦
listSummaries = false

# >>> Collection - End <<<

# Social icons
# ç¤¾äº¤åª’ä½“å›¾æ ‡
[[params.social]]
name = "x"
url = "https://x.com/rokcso/"

[[params.social]]
name = "github"
url = "https://github.com/rokcso/"

# Main menu pages
# é¦–é¡µèœå•
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "about"
url = "/about"

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

# >>> params - End <<<

# >>> taxonomies - Start <<<

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

# >>> taxonomies - End <<<

# >>> markup - Start <<<

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# >>> markup - End <<<